### ISSUE TITLE
README example code does not work

### ISSUE THREAD

**Issue by lhjamieson** [vermiculus/ssa-tool#20]
When trying to run the README example code that runs the actual algorithm, I get a "SyntaxError: can't assign to operator" on the must-unmark predicate's 3rd line.

**Comment by vermiculus** [comment]
Do you have a stack trace? It's working fine for me. (Just ran it clean on a new bundle to be sure.)

Per the README, the content of `./predicate/must-unmark` should be
```python
marked = v['marked']
neighbor_marked = any(map(lambda n: n['marked'], N))
RESULT = marked and neighbor_marked
```

I'm using Python 3.7.0.

**Comment by lhjamieson** [comment]
Here's the stack trace.  My must-unmark is as written above.  The error comes on the third line in the file.
```
Traceback (most recent call last):
  File "ssa.py", line 2, in <module>
    ssa.cli.run()
  File "/Users/lindsay/PycharmProjects/ssa-tool/ssa/cli.py", line 322, in run
    args.run_handler(**vars(args))
  File "/Users/lindsay/PycharmProjects/ssa-tool/ssa/cli.py", line 195, in run_algorithm
    iterations, num_graphs, **runargs)
  File "/Users/lindsay/PycharmProjects/ssa-tool/ssa/trial.py", line 152, in run
    algorithm.ensure_resolved()
  File "/Users/lindsay/PycharmProjects/ssa-tool/ssa/core.py", line 287, in ensure_resolved
    exe.ensure_resolved()
  File "/Users/lindsay/PycharmProjects/ssa-tool/ssa/core.py", line 60, in ensure_resolved
    self._define()
  File "/Users/lindsay/PycharmProjects/ssa-tool/ssa/core.py", line 68, in _define
    self._code = compile('\n'.join(lines), self.source_file, 'exec')
  File "indset.ssax/predicate/must-unmark", line 3
    RESULT = marked and neighbor_marked
    ^
SyntaxError: can't assign to operator
```

**Comment by vermiculus** [comment]
What version of Python are you using? Does the `RESULT` symbol have a special function in your environment?

**Comment by lhjamieson** [comment]
I'm using 3.6.3, but running in either the MacOS shell or PyCharm (same results).  I'll check to see if there's an update to Python.

**Comment by vermiculus** [comment]
Truly strange. From what I'm reading, that error is used for strange statements like `a/b=c`. However, `RESULT` is just a symbol (not an expression) so `=` should have no problem with it.

I suppose it's possible `compile()` is adding something extra in 3.6 that was taken away in 3.7, but that would be strange to me (and it isn't reflected in the error report). I'd try upgrading to 3.7 (like you mentioned) and I'll try reproducing with 3.6 on a VM. I'm having a heck of a time getting networkx installed on the VM, though – if you know of any tools that make it easier to manage python environments, I'm all ears.

**Comment by lhjamieson** [comment]
I'm having a heck of a time getting networkx installed on 3.7 because it keeps wanting to install it on the 3.6 from Anaconda.  Just did a poll of my students (who are using python for their project) and they don't know of any either.

**Comment by vermiculus** [comment]
There is [pyenv](https://github.com/pyenv/pyenv) – I might give that a tryout.

I just realized though that the CI tests are running 3.6: https://travis-ci.org/vermiculus/ssa-tool – those work fine, so I'm not sure what's going on in your environment. I might be able to give you a Vagrantfile that can run the tool – would that be of interest?

**Comment by vermiculus** [comment]
This [Vagrantfile](https://www.vagrantup.com/) should give you a working environment:

```ruby
Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')

$script = <<-SCRIPT
apt update && apt install python3-pip -y

git clone https://github.com/networkx/networkx.git
pushd .
cd networkx/ && git checkout networkx-2.2 && pip3 install -e .
popd

pushd .
git clone https://github.com/vermiculus/ssa-tool.git
cd ssa-tool/ && chown -R vagrant .
popd
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "shell", inline: $script
end
```

**Comment by ripark** [comment]
The trouble with Vagrant (cool tool that we were already considering for
programming languages) is that we need to get this to the point where it's
usable by less technical math-focused graph theorists. This is useful for
us right now in assessing where the ssa-tool is before we start to roll out
any GUI work.
---
Alan C. Jamieson, PhD
Associate Professor of Computer Science
Computer Science Program Director
St. Mary's College of Maryland

**Comment by vermiculus** [comment]
Ultimately I agree there should be some self-contained 'bundle' that can just be opened as an executable/app depending on OS. I don't think Vagrant should ever (or is currently) a requirement, though I don't have any good answers for why it's not working for you folks. Are you also able to reproduce this issue?

One option that may be worth exploring to avoid this issue is hosting, but that brings a host of its own problems.

**Comment by ripark** [comment]
I've not, but I'm also dragging my feet on setting up a virtual machine to play with this (my mac is on the fritz). I'll try to reproduce this during the weekend.

**Comment by ripark** [comment]
I wasn't able to reproduce the issue. I didn't use the vagrant file, just did the pip with requirements.txt and then ran make test. Seemed to work.

**Comment by lhjamieson** [comment]
All right.  After doing pip with requirements.txt and the make test, that works.  However, typing in, by hand, the example code from the README results in the above error and stack trace even after the make test ran successfully.  So, it looks there's something in the example code in the README that doesn't work.

**Comment by lhjamieson** [comment]
Running 'python3 ssa.py temp.ssax run 'Independent Set' gn,5 1000 100 works fine.  This makes me think there's a difference between the README example code and what's in the Makefile.  Will look at this tomorrow.

**Comment by vermiculus** [comment]
The only differences between the Makefile and the README code I can identify are:
* The README version uses 'staging files' (instead of piping directly to stdin like the Makefile)
* The Makefile version has spurious spaces at the end of every line but the last
* The Makefile version lacks terminal newlines

If you copy and paste this shell script into your terminal, do you get the same error? (I'm avoiding staging files here.)

```sh
# Predicates have access to node (v) and neighborhood (N) attributes
python3 ssa.py indset.ssax new predicate can-mark -p marked bool <<EOF
marked = v['marked']
neighbor_marked = any(map(lambda n: n['marked'], N))
RESULT = not (marked or neighbor_marked)
EOF

python3 ssa.py indset.ssax new predicate must-unmark -p marked bool <<EOF
marked = v['marked']
neighbor_marked = any(map(lambda n: n['marked'], N))
RESULT = marked and neighbor_marked
EOF

# Moves can set node state
python3 ssa.py indset.ssax new move mark -p marked bool <<EOF
v['marked'] = True
EOF

python3 ssa.py indset.ssax new move unmark -p marked bool <<EOF
v['marked'] = False
EOF

# create a new algorithm
python3 ssa.py indset.ssax new algorithm 'Independent Set'

# define rules for that algorithm
python3 ssa.py indset.ssax add-rule-to 'Independent Set' can-mark mark
python3 ssa.py indset.ssax add-rule-to 'Independent Set' must-unmark unmark

# run the algorithm
python3 ssa.py indset.ssax run 'Independent Set' gn,5 1000 100
```

**Comment by lhjamieson** [comment]
Obviously, I can't type. Copying the above and pasted it in at the terminal worked fine.

**Comment by vermiculus** [comment]
😄
