### ISSUE TITLE
Should a move be able to read its neighbors' states?

### ISSUE THREAD

**Issue by vermiculus** [vermiculus/ssa-tool#9]
This is more of a theory question to the definition of self-stabilizing algorithms.  I see no reason why a move shouldn't be able to do so.  Is this valid?

It may be a moot point since each read could be expanded into a finite or infinite number of predicate-move pairs -- one for each possible value.  It's the uncountable-infinite case that worries me from a math side.

**Comment by vermiculus** [comment]
If we want to do this, `Move` should be given the neighbors as readable state.

**Comment by ripark** [comment]
Yes - under the simplest version each node can only read it's own data, but researchers found it to be very limiting. An extension was added for flags and other data to be readable across neighbors.
